feat: button component
harshitadaswani/CRYPTO-UI pull request #5
Opened 2022-02-03 20:10 UTC by harshitadaswani

- added container buttons
- added icon button
- added outline buttons

2022-02-03 20:20 UTC, JantuDeb requested changes
Suggested some changes.

2022-02-03 20:20 UTC, JantuDeb commented on components/button.css
> +}
Use a `.btn` class for common properties.

2022-02-03 20:20 UTC, JantuDeb commented on components/button.css
> +}
Same as above use a `.outline` class

2022-02-03 20:25 UTC, t007rushi requested changes
make suggested one

2022-02-03 20:25 UTC, t007rushi commented on components/button.css
> +.btn-icon {
make a utility class for this

2022-02-03 20:25 UTC, t007rushi commented on components/button.css
> +.btn-disabled {
same as above

2022-02-03 20:25 UTC, t007rushi commented on components/button.css
> +.outline-disabled {
same as above

2022-02-03 22:02 UTC, harshitadaswani commented on components/button.css
> +.btn-disabled {
done

2022-02-03 22:08 UTC, JantuDeb approved these changes
Now it's fine as you have made all the required changes, you can merge this PR.

2022-02-04 05:12 UTC, t007rushi approved these changes

2022-02-05 19:50 UTC, merged